apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
    spec:
      containers:
        - name: pihole
          image: pihole/pihole:latest
          env:
            - name: TZ
              value: "UTC"
            - name: WEBPASSWORD
              valueFrom:
                secretKeyRef:
                  name: pihole-password
                  key: WEBPASSWORD
          ports:
            - containerPort: 80
            - containerPort: 53
