apiVersion: v1
kind: Service
metadata:
  name: pihole

spec:
  type: LoadBalancer

  ports:
    - name: http
    - port: 80
      targetPort: 80
      protocol: TCP
      
    - name: dns  
    - port: 53
      targetPort: 53
      protocol: UDP

  selector:
    app: pihole
