apiVersion: v1
kind: Service
metadata:
  name: pihole
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
    - port: 53
      targetPort: 53
      protocol: UDP
  selector:
    app: pihole
