apiVersion: apps/v1
kind: Deployment
metadata:
  name: posgresql
  namespace: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgresql
        image: postgres:15
        env:
        - name: POSTGRES_DB
          value: nextcloud
        - name: POSTGRES_USER
          value: admin
        - name: POSTGRES_PASSWORD
          value: secret #replace with secret
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-storage
          mountPaths: /var/lib/postgresql/data
      volumes:
      - name: postgres-storage
        persistendVolumeClaim:
          claimName: postgres-pvc


              
