apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      containers:
      - name: nextcloud
        image: nextcloud:latest
        ports:
        - containerPort: 80
        env:
        - name: POSTGRES_HOST
          value: postgresql
        - name: POSTGRES_DB
          value: nextcloud
        - name: POSTGRES_USER
          value: admin
        - name: POSTGRES_PASSWORD
          value: secret #replace with secret
        - name: NEXTCLOUD_ADMIN_USER
          value: admin
        - name: NEXTCLOUD_ADMIN_PASSWORD
          value: secret #replace with secret
        - name: NEXTCLOUD_TRUSTED_DOMAINS
          value: "192.168.0.250 localhost"
        volumeMounts: 
        - name: nextcloud-storage
          mountPath: /var/www/html
      volumes:
      - name: nextcloud-storage
        persistentVolumeClaim:
          claimName: nextcloud-pvc
