apiVersion: v1
kind: Service
metadata:
  name: nextcloud
  namespace: nextcloud
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.0.250
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.0.250
  selector:
    app: nextcloud
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  - name: https
    port: 443
    targetPort: 80
    protocol: TCP
